{
 "title": "RecordBox",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -1d) \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"epgstation\" and\r\n    r._field == \"reserve\"\r\n  )\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Drop",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Pkts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -1w) // 直近の1週間を指定\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tsfile_info\" and\r\n    r._field == \"drop\"\r\n  )\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Scramble",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Pkts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "current_time = now()\r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: -1w)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tsfile_info\" and\r\n    r._field == \"scramble\"\r\n  )\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r._value > 100 then 100 else if r._value < 0 then 0 else r._value\r\n  }))\r\n  |> map(fn: (r) => ({ r with _time: current_time }))\r\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    (r._field == \"cpu_usage\")\r\n  )\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"mem_usage\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "温度",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    (r._field == \"cpu_temp\")\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Device",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunerstate\" and r[\"_field\"] == \"status\")\r\n  |> last()\r\n  |> group(columns: [\"device\"]) \r\n  |> map(fn: (r) => ({_time: r._time, name: r.device, status: r._value}))\r\n  |> sort(columns: [\"name\"] )"
    }
   ]
  },
  {
   "title": "空き容量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -7d) \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"free_disk\"\r\n  )\r\n  |> aggregateWindow(every: 5m, fn: mean)\r\n  "
    }
   ]
  },
  {
   "title": "History & Drop",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tsfile_info\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"cpu_usage\"\r\n  )\r\n  |> aggregateWindow(every: 5m, fn: mean)"
    },
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"mem_used\"\r\n  )\r\n  |> aggregateWindow(every: 5m, fn: mean)  \r\n"
    }
   ]
  },
  {
   "title": "録画/エンコード稼働状況",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"epgstation\" and\r\n    r._field == \"encoding\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"epgstation\" and\r\n    r._field == \"recording\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Drop / Scramble 推移",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tsfile_status\" and\r\n    r._field == \"drop\"\r\n  )\r\n"
    },
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tsfile_status\" and\r\n    r._field == \"scramble\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r._value > 100 then 100 else if r._value < 0 then 0 else r._value\r\n  }))"
    }
   ]
  },
  {
   "title": "温度推移",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"cpu_temp\"\r\n  )\r\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  }
 ]
}