{
 "title": "RecordBox",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    (r._field == \"cpu_usage\")\r\n  )\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "温度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    (r._field == \"cpu_temp\")\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "空き容量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"free_disk\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "録画予約数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"epgstation\" and\r\n    (r._field == \"reserve\")\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "メモリ使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"mem_usage\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU 使用率推移",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"cpu_usage\"\r\n  )"
    }
   ]
  },
  {
   "title": "空き容量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"free_disk\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "録画中",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"epgstation\" and\r\n    r._field == \"recording\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "温度推移",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"cpu_temp\"\r\n  )"
    }
   ]
  },
  {
   "title": "エンコードタイプ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"encode_task\" and\r\n    r._field == \"exist_gst\"\r\n  )\r\n  |> map( fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Gstreamer\" } ))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"encode_task\" and\r\n    r._field == \"exist_ffmpeg\"\r\n  )\r\n  |> map( fn: (r) => ({ _value: r._value, _time: r._time, _field: \"ffmpeg\" } ))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Disk R/W wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"r_wait\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"machine\" and\r\n    r._field == \"w_wait\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}